import fs from 'fs';
import path from 'path';

async function setup() {
    console.log('--- VoxNexus Ngrok Auto-Config ---');

    try {
        const response = await fetch('http://localhost:4040/api/tunnels');
        const data = await response.json();

        // With single tunnel config, we expect just one public URL
        const tunnel = data.tunnels.find(t => t.config.addr.includes('5173'));

        if (!tunnel) {
            console.log('[-] Frontend tunnel not found. Make sure ngrok is running.');
            return;
        }

        const publicUrl = tunnel.public_url;
        console.log(`[+] Public URL: ${publicUrl}`);

        const envPath = path.join(process.cwd(), 'client', '.env.local');
        // We set BACKEND_URL to the same public URL so requests are proxied by Vite
        const envContent = [
            '# Auto-generated by setup-ngrok.js',
            `VITE_BACKEND_URL=${publicUrl}`,
            `VITE_LIVEKIT_URL=wss://kimo-zg71lj4i.livekit.cloud`,
            ''
        ].join('\n');

        fs.writeFileSync(envPath, envContent);
        console.log('[+] client/.env.local updated with Ngrok URL');
        console.log('\nYou can now access the app at:');
        console.log(`👉 ${publicUrl}`);

    } catch (error) {
        console.log('[-] Ngrok API not reachable yet. Please start ngrok in another terminal.');
        console.error(error);
    }
}

setup();
